### ISSUE TITLE
docker workflow isn't working

### ISSUE THREAD

**Issue by Vad1mo** [automaticmode/active_workflow#1]
in contrast to what is described in the readme the docker workflow is not working 

```
git clone git@github.com:automaticmode/active_workflow.git
cd active_workflow 
docker-compose up

Pulling active_workflow (local/active_workflow:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.
```

**Comment by vidas** [comment]
Thank you for your feedback!

Unfortunately README wasn't clear that `docker-compose` requires you to build image as a separate step. I've fixed the docker workflow so that `docker-compose up` works as expected - out of the box right after git clone. Sorry for your troubles!

Fixed in https://github.com/automaticmode/active_workflow/commit/5154e1f1da5a916bb7b67837ff15d0271fe40b5d.
